Write API test for gorest.co.in
HaykMelikyan/EPAMHomework pull request #10
Opened 2021-04-09 12:52 UTC by HaykMelikyan

2021-04-09 13:13 UTC, David91 commented on src/test/java/GorestAPITest.java
> +        delete(postId, header);
This is a post test action.

2021-04-11 18:06 UTC, chandranik90 requested changes

2021-04-11 18:06 UTC, chandranik90 commented on src/test/java/GorestAPITest.java
> +    Header header = new Header("Authorization", "Bearer 53b517c08020390a239e02b19714d9e6665715878869e69f811d3e81e8a0029a");
Always use access modifiers

2021-04-11 18:06 UTC, chandranik90 commented on src/main/java/gorestAPI/APIRequest.java
> +    public APIRequest() {
Avoid extra complexity of the code. 3 out of 4 constructors are not ever used. Just remove them and keep the code as simple as possible

2021-04-11 18:06 UTC, chandranik90 commented on src/main/java/gorestAPI/APIRequest.java
> +    public void setHeader(Header header) {
Those setter methods are also redundant. They break the incapsulation and do not actually bring any value in your case

2021-04-11 18:06 UTC, chandranik90 commented on src/main/java/gorestAPI/APIRequest.java
> +                .when()
The `when` and `then` are useful only if you perform some built-in validations here. In this case, they are just useless.

2021-04-11 18:06 UTC, chandranik90 commented on src/main/java/gorestAPI/APIRequest.java
> +                .extract()
You don't need to explicitly extract the response. Instead, you may use the `thenReturn` method.

2021-04-11 18:06 UTC, chandranik90 commented on src/main/java/gorestAPI/User.java
> +@NoArgsConstructor
The `NoArgsConstructor` is useless in this case, because the `User` object is being initialized only by all arguments. So, you can replace it by `AllArgsConstructor` and remove the explicit constructor.

2021-04-11 18:06 UTC, chandranik90 commented on src/test/java/GorestAPITest.java
> +        User user = new User("HaykPost Test", "HaykPostn1@test.io", "Male", "Active");
Though your test deletes the created user, there is always a risk of test failure, which will bring to data issue in your test later. Also, there is a risk, that the same e-mail has been already used by someone else.
In such cases, there is a good practice to append a timestamp to the username. You can get the current date-time and append it and get a unique name always.

2021-04-11 18:06 UTC, chandranik90 commented on pom.xml
> +            <artifactId>json-schema-validator</artifactId>
This dependency is never used

2021-04-11 18:06 UTC, chandranik90 commented on pom.xml
> +            <artifactId>json-path</artifactId>
This dependency is transitive for `rest-assured`. So, it's redundant

2021-04-11 18:36 UTC, HaykMelikyan commented on pom.xml
> +            <artifactId>json-schema-validator</artifactId>
That dependency adds jackson libraries, so I can use User type object as RestAssured body() method argument.

2021-04-12 08:35 UTC, HamTorosyan requested changes

2021-04-12 08:35 UTC, HamTorosyan commented on src/main/java/gorestAPI/APIRequest.java
> +    public int post(User user) {
In this way, you narrow your method usage, so it will always post `User`, usually, these methods should have wider usage.

2021-04-12 08:35 UTC, HamTorosyan commented on src/main/java/gorestAPI/APIRequest.java
> +public class APIRequest {
please use the naming convention `ApiRequest`

2021-04-12 08:35 UTC, HamTorosyan commented on src/test/java/GorestAPITest.java
> +public class GorestAPITest {
please use the naming convention `GoRestApiTests`

2021-04-12 08:35 UTC, HamTorosyan commented on src/test/java/GorestAPITest.java
> +    private Header header = new Header("Authorization", "Bearer 53b517c08020390a239e02b19714d9e6665715878869e69f811d3e81e8a0029a");
This header used for authentication purpose only, it doesn't change between tests, it shouldn't be in test layer, better to organize this in Request/Response layer

2021-04-12 08:35 UTC, HamTorosyan commented on src/test/java/GorestAPITest.java
> +    public void APITestGorest() {
method naming convention didn't keep, also method name isn't meaningful

2021-04-12 08:35 UTC, HamTorosyan commented on src/test/java/GorestAPITest.java
> +    public String getField(Response response, String path) {
this method have no usage outside of the class, so it should be `private`

2021-04-14 19:37 UTC, HamTorosyan approved these changes
Please have a look to the comments for future

2021-04-14 19:37 UTC, HamTorosyan commented on src/main/resources/ApiRequestProp.properties
> +AUTHTORIZATION_TOKEN=Bearer 53b517c08020390a239e02b19714d9e6665715878869e69f811d3e81e8a0029a
```suggestion
AUTHORIZATION_TOKEN=Bearer 53b517c08020390a239e02b19714d9e6665715878869e69f811d3e81e8a0029a
```

2021-04-14 19:37 UTC, HamTorosyan commented on src/main/java/gorestAPI/ApiRequest.java
> +        RestAssured.baseURI = propReader.getProperty("BASE_URI");
This actions doesn't relate to `ApiRequest` object creation, so I would paste this inside TestNG `@Before___()` method

2021-04-14 19:37 UTC, HamTorosyan commented on src/test/java/GoRestApiTest.java
> +    public void goRestPostUserTest() {
each test method should be responsible for a single functionality check, so I suggest splitting functionalities over different `@Test` methods.

2021-04-14 19:37 UTC, HamTorosyan commented on src/test/java/GoRestApiTest.java
> +        Response deleteResponse = apiRequest.delete(endPoint + userId);
What if the backend returns the expected status code but the user doesn't delete it? I suggest validating user deletion by getting that user by ID and making sure that the user doesn't exist, it should return 404 and a message.

2021-04-15 09:53 UTC, merged