Test greetz.nl website
HaykMelikyan/EPAMHomework pull request #5
Opened 2021-03-23 15:25 UTC by HaykMelikyan

-Add item to favorites and check it's appearance
-Change amount and check total price calculation

2021-03-23 20:17 UTC, HamTorosyan requested changes
also use more meaningful branch name according to some conventions

2021-03-23 20:17 UTC, HamTorosyan commented on src/test/java/greetzWebsiteTest.java
> +public class greetzWebsiteTest {
Class name starts with Capital letter

2021-03-23 20:17 UTC, HamTorosyan commented on src/test/java/greetzWebsiteTest.java
> +        String productNameExpected = productItem.findElement(By.className("b-products-grid__item-title")).getText();
`productNameExpected` is not wrong, but `expectedProductName` is more useful, the same for price.

2021-03-23 20:17 UTC, HamTorosyan commented on src/test/java/greetzWebsiteTest.java
> +        Assert.assertEquals(sidebar.findElement(By.className("price-block")).getText(), productPriceExpected,
Unreachable line, if Test fails on line 44, to bypass it use `SoftAssert()`

2021-03-23 20:17 UTC, HamTorosyan commented on src/test/java/greetzWebsiteTest.java
> +        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
You have code repetition on 13, 14 and 59, 60 lines, I would suggest declaring instance of WebDriver outside of all methods (class level), instantiate it inside login method, and use in other methods, as you perform login step in the beginning of other methods

2021-03-23 21:05 UTC, HaykMelikyan commented on src/test/java/greetzWebsiteTest.java
> +public class greetzWebsiteTest {
fixed

2021-03-23 21:06 UTC, HaykMelikyan commented on src/test/java/greetzWebsiteTest.java
> +        String productNameExpected = productItem.findElement(By.className("b-products-grid__item-title")).getText();
fixed

2021-03-23 21:06 UTC, HaykMelikyan commented on src/test/java/greetzWebsiteTest.java
> +        Assert.assertEquals(sidebar.findElement(By.className("price-block")).getText(), productPriceExpected,
fixed

2021-03-23 21:06 UTC, HaykMelikyan commented on src/test/java/greetzWebsiteTest.java
> +        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
fixed

2021-03-24 14:38 UTC, chandranik90 requested changes

2021-03-24 14:38 UTC, chandranik90 commented on src/test/java/greetzWebsiteTest.java
> +public class greetzWebsiteTest {
Class name should start by upper-case

2021-03-24 14:38 UTC, chandranik90 commented on src/test/java/GreetzWebsiteTest.java
> +        String ExpectedProductName = productItem.findElement(By.className("b-products-grid__item-title")).getText();
Variable name should start by lower-case

2021-03-24 14:38 UTC, chandranik90 commented on src/test/java/GreetzWebsiteTest.java
> +        driver.findElement(By.cssSelector("a[class = 'page-header__navigation-item item-user']")).click();
Better to have at least half a second sleep between those two steps. It's obviously fast, but test potentially can fail, since the test execution can be even faster

2021-03-24 14:38 UTC, chandranik90 commented on src/test/java/GreetzWebsiteTest.java
> +        assertion.assertEquals(sidebar.findElement(By.tagName("h1")).getText(), ExpectedProductName,
`h1` is not a good locator here. It's too fragile and can be changed at any time. You could rely on the class name instead.
Another important thing. Try to avoid nested complicated expressions. They are error-prone, unreadable, and hardly debuggable.

2021-03-24 14:38 UTC, chandranik90 commented on src/test/java/GreetzWebsiteTest.java
> +        String singlePrice = priceBlock.findElement(By.className("price-normal")).getText().substring(2);
It's better to use regular expressions. Anyway, this is not an issue, just as a best practice

2021-03-24 17:09 UTC, chandranik90 approved these changes

2021-03-24 17:09 UTC, chandranik90 commented on src/test/java/GreetzWebsiteTest.java
> +        assertion.assertEquals(actualProductName, expectedProductName,
Seems, you forgot `assertAll` for Soft Assert. This assertion will not execute

2021-03-24 17:09 UTC, chandranik90 commented on src/test/java/GreetzWebsiteTest.java
> +        singlePrice = singlePrice.replaceAll("[^(\\d|\\,)]", "");
`,` is not a special character for RegExp pattern. So, you don't need backslash to identify it.

2021-03-24 17:09 UTC, chandranik90 commented on src/test/java/GreetzWebsiteTest.java
> +            e.printStackTrace();
Mark throws in method signature as you did in test methods

2021-03-26 14:16 UTC, merged