Test amazon.com website
HaykMelikyan/EPAMHomework pull request #7
Opened 2021-03-31 15:05 UTC by HaykMelikyan

- Add amazonpages package
- Add book searching and writer page test

2021-03-31 15:07 UTC, HaykMelikyan commented
The test sometimes fails, because search results do not always contain books only from the searched writer.

2021-04-01 18:10 UTC, David91 requested changes

2021-04-01 18:10 UTC, David91 commented on src/main/java/amazonpages/BookSearchResultsPage.java
> +            "/div[@class='a-row a-size-base a-color-secondary']";
Why these selectors are so long ? Isn't there any option to optimize them ?

2021-04-01 18:10 UTC, David91 commented on src/main/java/amazonpages/BookSearchResultsPage.java
> +        pageUrl = "https://www.amazon.com/s?k=" + writerName + "&i=stripbooks-intl-ship&ref=nb_sb_noss";
It'd be better for page objects to keep only their parts of URL, not the whole one.

2021-04-01 18:10 UTC, David91 commented on src/main/java/amazonpages/BookSearchResultsPage.java
> +        return writersPage;
It's a good approach to return the page reference, where you are being redirected, but your method in BookSearchResultsPage shouldn't be responsible for writersPage successful loading. So it'd be better to return `new WritersPage(driver, writerName)` and then in test method wait till page will be loaded.

2021-04-01 18:10 UTC, David91 commented on src/main/java/amazonpages/HomePage.java
> +        searchDropdownElement.click();
It'd be safe to have a wait, which will wait until dropdown content appear. When network will be slow or overloaded, test can randomly fail.

2021-04-01 18:10 UTC, David91 commented on src/main/java/amazonpages/HomePage.java
> +        bookSearchResultsPage.waitUntilPageLoads();
The same comment, as written for 58th line.

2021-04-01 18:10 UTC, David91 commented on src/main/java/amazonpages/WritersPage.java
> +        bookSearchResultsPage.goToFirstWritersPage();
open() method in HomePage looked more appropriate. Write this method in that way, because open() method should be responsible only for opening and maximum returning a page as well.

2021-04-01 19:36 UTC, HaykMelikyan commented on src/main/java/amazonpages/WritersPage.java
> +        bookSearchResultsPage.goToFirstWritersPage();
I couldn't find any link pattern for a specific writer page, to open that page with just `driver.get()` method using appropriate link, so I'm doing it by searching writer's name and clicking on the first result's writer link. Anyway, I don't use that `open()` method anywhere in the test, so it can be removed.

2021-04-02 11:07 UTC, David91 approved these changes

2021-04-02 11:07 UTC, David91 commented on src/main/java/amazonpages/HomePage.java
> +    private String pageUrl = BASE_URL;
Why to have static BASE_URL ? Just have an instance BASE_URL variable and remove pageUrl

2021-04-02 11:07 UTC, David91 commented on src/main/java/amazonpages/WritersPage.java
> -
You can have open method in WritersPage as well and write it in a way we discussed at today's session.

2021-04-02 12:21 UTC, merged